"""Technical slicing/padding only; all source artwork was generated by ImageGen."""
from PIL import Image,ImageDraw
from pathlib import Path
import shutil
root=Path(__file__).resolve().parents[1]
src=root/'assets/art/source'
out=root/'assets/art'; originals=out/'source';originals.mkdir(exist_ok=True)
names=['mage','skeleton','archer','zombie','ghoul','sorcerer','knight','imp','ghost','king','plague','demon','lich','merchant','teacher','healer']
props=['chest','chest_open','torch','urn','portal','stairs','gold','health','mana','staff','ring','book','missile','fire','lightning','ice']
def slice_atlas(filename,ids):
 im=Image.open(src/filename).convert('RGBA');print(filename,im.size,'alpha',im.getchannel('A').getextrema())
 # Source atlases remain untouched.
 for i,id in enumerate(ids):
  x=i%4;y=i//4
  crop=im.crop((round(x*im.width/4),round(y*im.height/4),round((x+1)*im.width/4),round((y+1)*im.height/4)))
  bbox=crop.getchannel('A').point(lambda v:255 if v>25 else 0).getbbox()
  if bbox:crop=crop.crop(bbox)
  crop.thumbnail((236,236),Image.Resampling.LANCZOS)
  canvas=Image.new('RGBA',(256,256));canvas.alpha_composite(crop,((256-crop.width)//2,248-crop.height))
  canvas.save(out/(id+'.png'))
slice_atlas('characters.png',names)
slice_atlas('props.png',props)
im=Image.open(src/'materials.png')
for i,id in enumerate(['floor_stone','wall','floor_village','floor_crypt']):
 x=i%2;y=i//2
 im.crop((x*im.width//2,y*im.height//2,(x+1)*im.width//2,(y+1)*im.height//2)).resize((512,512),Image.Resampling.LANCZOS).save(out/(id+'.png'))
contact=Image.new('RGB',(1024,768),(26,36,44));draw=ImageDraw.Draw(contact)
for i,id in enumerate(names+props):
 im=Image.open(out/(id+'.png'));im.thumbnail((105,105))
 x=(i%8)*128;y=(i//8)*180
 contact.paste(im,(x+12,y+20),im);draw.text((x+8,y+138),id,fill=(235,225,201))
contact.save(root/'outputs/art_contact_sheet.jpg')
